# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3529edd426a205d40a88eca02199ad96"
name = "discount-and-shipping-rework"
application_url = "https://generart.fit:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://discount.generart.fit/api/auth" ]
